### ISSUE TITLE
NoMethodError for user with hypen in github username

### ISSUE THREAD

**Issue by abhishekpillai** [learn-co/learn-submit#1]
```
➜  first-lab-ruby-learn-cli-nitrous-q-000 git:(master) learn submit
Adding changes...
Committing changes...
It looks like you have no changes to commit. Will still try updating your submission...
Pushing changes to GitHub...
Submitting lesson...
/usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/learn-submit-1.1.7/lib/learn_submit/submission/git_interactor.rb:28:in `repo_name': undefined method `[]' fo
r nil:NilClass (NoMethodError)
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:57:in `submit!'
        from /usr/local/opt/rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/learn-submit-1.1.7/lib/learn_submit/submission.rb:25:in `create'
```

https://flatiron-staff.slack.com/archives/escalation/p1451867601001785

**Comment by loganhasson** [comment]
fixed by 6207cd59f8bcabbe19d6f6a537308bebb79a0bff
